server {
    listen 80;
    server_name delicatto.infinyatecnologia.tech www.delicatto.infinyatecnologia.tech;

    resolver 127.0.0.11 valid=10s;

    if ($host ~* ^www\.(.*)) {
        return 301 http://$1$request_uri;
    }

    location / {
        proxy_pass http://delicatto-site:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
    }
}
