version: "3.9"

networks:
  delicatto:
    driver: bridge
  proxy_network:
    external: true

services:
  delicatto-site:
    image: localhost:5000/delicatto-site:latest
    container_name: delicatto-site
    restart: unless-stopped
    ports:
      - "7900:80"
    networks:
      - delicatto
      - proxy_network
